apiVersion: apps/v1
kind: Deployment
metadata:
  name: barbershop-gateway
  labels:
    app: gateway
spec:
  replicas: {{ .Values.gateway.deployment.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "{{ .Values.gateway.service.port }}"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: ramzi611/barbershop-gateway:latest
        ports:
        - containerPort: {{ .Values.gateway.service.port }}
        env:
          - name: PRODUCTION
            value: "true"
          - name: JWT_SECRET
            value: {{ .Values.gateway.deployment.jwt }}
          - name: POSTS_MICRO_HOST
            value: {{ .Values.posts.service.name }}
          - name: POSTS_MICRO_PORT
            value: "{{ .Values.posts.service.port }}"
          - name: AUTH_MICRO_HOST
            value: {{ .Values.authentication.service.name }}
          - name: AUTH_MICRO_PORT
            value: "{{ .Values.authentication.service.port }}"