apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Values.gateway.service.name }}
            port:
              number: {{ .Values.gateway.service.port }}
        path: /
        pathType: Prefix