apiVersion: v1
kind: Service
metadata:
  name: {{.Values.gateway.service.name}}
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: {{.Values.gateway.service.port}}
    targetPort: {{.Values.gateway.service.port}}
  type: ClusterIP