apiVersion: v1
kind: Service
metadata:
  name: {{.Values.posts.service.name}}
spec:
  selector:
    app: posts
  ports:
  - name: http
    port: {{.Values.posts.service.port}}
    targetPort: {{.Values.posts.service.port}}
  type: ClusterIP