apiVersion: apps/v1
kind: Deployment
metadata:
  name: barbershop-db
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: postgres:14.1-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: barbershopuser
          - name: POSTGRES_PASSWORD
            value: barbershoppasswd
          - name: POSTGRES_DB
            value: barbershopdb